name: campus_explorer_
description: Campus Explorer Map Application
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  json_annotation: ^4.9.0
  flutter_polyline_points: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/campus_data.json
    - assets/map_style_midnight.json
    - assets/pin_start.png
    - assets/pin_end.png
